### ISSUE TITLE
[Feature Request] Real-Time polling

### ISSUE THREAD

**Issue by ballPointPenguin** [NuCivic/recline.view.nvd3.js#6]
Perhaps some websockets integration?
cc: @zeckalpha

**Comment by zeckalpha** [comment]
Polling should work fine for just a couple rows at a time... less than 10 events per second or so.

**Comment by zeckalpha** [comment]
It looks like the datasets are Backbone models, so this shouldn't be too difficult.

**Comment by topicus** [comment]
Yes, since those are backbone models it would be easy to update a chart when data changes. 

However, currently the render function re-instantiate nvd3 charts each time model changes which can lead to an annoying flickering, or worse, re-run initial animation if it's set.

I've created a function called lightUpdate that eventually will replace the current render function but I experienced some issues trying to update the chart with some configurations without re-instantiate the nvd3 chart (I currently don't remember which). 

I will modify that when I'm less slammed.
